### PR TITLE
Support the standard grunt files config for specifying files.

### PR DESCRIPTION
**Pull request by russelldavis**

### CODE REVIEW

**Comment by yoniholmes** [comment]
Thanks for this and apologies for the delays in responding. This is a change I had been considering for a while, so thanks for sending a pull request. It does however break existing implementations, so I haven't immediate plans to include this. I will consider it for any upcoming minor or major updates of the plugin though - that could be weeks or months away.

Thanks again, 

Jonathan

**Comment by russelldavis** [comment]
Curious, can you point out specifically what this breaks on existing implementations? (Note that the functional tests continue to pass without any changes.)

**Comment by bivihoba** [comment]
+1

**Comment by yoniholmes** [comment]
Hi Russell, 

Sorry about the delay getting back to you - have been away but it's a poor excuse. What I meant was, and tell me if I've misunderstood, introducing the change is backwards incompatible with existing gruntfile config set ups. Anyone updating to this version of grunt-text-replace will need to change their gruntfiles (ie. place src and dest inside a files object). 

I hadn't plan to introduce backwards incompatible updates for a while was all... 

Cheers, 

Jonathan

**Comment by russelldavis** [comment]
@yoniholmes It should be compatible. Configs are normalized using [grunt.task.normalizeMultiTaskFiles](http://gruntjs.com/api/grunt.task#grunt.task.normalizemultitaskfiles), which supports the old style (i.e., the [compact format](http://gruntjs.com/configuring-tasks#compact-format)).

Again: your functional tests, which use the old style config (and haven't been modified), continue to pass. If it was backwards incompatible, those should be failing.

**Comment by russelldavis** [comment]
closing my pull requests in abandoned projects

**Pull request closed without merging**
