### PR TITLE
Provides an expand option

### PR DESCRIPTION
**Pull request by micahblu**
This option allows wildcard directory matches from src pattern to build in dest

### CODE REVIEW

**Comment by micahblu** [comment]
Hi there, the build failure appears to be from npm install issue. Same as before the pr

**Comment by yoniholmes** [comment]
Hey just wanted to say sorry for the delays - have been particularly busy. Still going to be a little while before I can review and merge, there's a queue of pull requests so want to get through these at the same time. Thanks, Jonathan

**Comment by micahblu** [comment]
closed by accident, was just saying no worries, I know how it goes. Thanks

**Comment by fantapop** [comment]
Would be nice to see this merged.  For now i'm using the work around to copy the file tree in step one and in place edit for step 2.

**Comment by yoniholmes** [comment]
Hi there @micahblu and @fantapop, thanks for the messages. Note: I still don't see an open pull request. If you're keen for this, please go ahead and reopen / or create a new pull request. Also note that it's important that any feature has suitable tests, so please ensure the new feature is covered by tests and doesn't break any old ones. Many thanks & Happy New Year :)  Jonathan

**Pull request closed without merging**
